
  - name: Enable cmdlist
    lineinfile:
      dest: /etc/env.d/02distcc
      line: 'DISTCC_CMDLIST="/etc/distcc/cmdlist"'
      regexp: "^DISTCC_CMDLIST.*"
      state: "present"
    when: "{{ distcc.cmdlist|length }}"
    register: cmdlist_env
    tags: [config]

  - shell:
      cmd: env-update
    changed_when: False
    when: "{{ cmdlist_env.changed }}"
    notify:
      - Restart distccd
    tags: [config]

  - name: Check /etc/distcc/cmdlist
    copy:
      content: ""
      dest: "/etc/distcc/cmdlist"
      force: no
    when: "{{ distcc.cmdlist|length }}"
    tags: [config]

  - name: Set up /etc/distcc/cmdlist
    lineinfile:
      dest: /etc/distcc/cmdlist
      line: "{{ item }}"
      state: "present"
    with_items: "{{ distcc.cmdlist }}"
    when: "{{ distcc.cmdlist|length }}"
    notify:
      - Restart distccd
    tags: [config]

  - name: Set up server
    lineinfile:
      dest: /etc/conf.d/distccd
      line: "DISTCCD_OPTS=\"${DISTCCD_OPTS} {{ item }}\""
    with_items: "{{ distcc.server_options }}"  
    notify:
      - Restart distccd
    tags: [config]

  - name: Setup "distccd" service
    service:
      name: "distccd"
      enabled: "yes"
      state: "started"
      runlevel: "default"
    tags: [services]

  - meta: flush_handlers
